# -*- coding: utf-8 -*-
"""ShapeAI_CyberSecurity_Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14NS4uVlz2odgFZ9TfBSagL3ryAlliJUU

Requests module of python allows you to make an http/https requests to the website / server.
"""

import requests
from datetime import datetime

api_key = "4a9ad3dd4bdf6af3e7a1177ac548c238"

location = input("Enter the city name: ")

complete_api_link = f"https://api.openweathermap.org/data/2.5/weather?q={location}&appid={api_key}"
api_link = requests.get(complete_api_link)
api_data = api_link.json()

print(dir(api_link))
# this dir() gives the list of methods available with the requests module

# creating temporary variable to store data
temperature_city = ((api_data['main']['temp']) - 273.15)
weather_description = api_data['weather'][0]['description']
humidity = api_data['main']['humidity']
wind_speed = api_data['wind']['speed']
date_time = datetime.now().strftime("%d %b %Y | %I:%M:%S %p")

print(f"-----------------------------Weather data of : {location}-----------------------------")
print(f"Weather statistics for - {location.upper()} || {date_time}")
print(f"--------------------------------------------------------------------------------------")

print(f"Current temperature is : {(temperature_city):.2f} deg C")  # .2f - upto two decimal points
print(f"Current weather description : {weather_description}")
print(f"Current Humidity : {humidity} %")
print(f"Current Wind Speed : {wind_speed} kmph")

f = open(f"weather_data_of_{location}.txt", "w")
f.write(f"-----------------------------Weather data of : {location}-----------------------------\n")
f.write(f"Weather statistics for - {location.upper()} || {date_time} \n")
f.write(f"--------------------------------------------------------------------------------------\n")
f.write("\n\n\n")

f.write(f"Current temperature is : {(temperature_city):.2f} deg C \n")  
f.write(f"Current weather description : {weather_description} \n")
f.write(f"Current Humidity : {humidity} % \n")
f.write(f"Current Wind Speed : {wind_speed} kmph \n")
f.write("\n\n\n")

f.close()